// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_TabPage1;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Chart2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Container3;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_LabelBtn1;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_LabelBtn2;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_LabelBtn3;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_LabelBtn4;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_TabPage2;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_TaskContainer;
extern lv_obj_t * ui_labeltask;
extern lv_obj_t * ui_DropdownTemperature;
extern lv_obj_t * ui_DropdownCondition;
extern lv_obj_t * ui_ConditionValue;
extern lv_obj_t * ui_LabelDo;
extern lv_obj_t * ui_DropdownAction;
extern lv_obj_t * ui_ActionValue;
extern lv_obj_t * ui_TaskContainer1;
extern lv_obj_t * ui_labeltask1;
extern lv_obj_t * ui_DropdownTemperature1;
extern lv_obj_t * ui_DropdownCondition1;
extern lv_obj_t * ui_ConditionValue1;
extern lv_obj_t * ui_LabelDo1;
extern lv_obj_t * ui_DropdownAction1;
extern lv_obj_t * ui_ActionValue1;
extern lv_obj_t * ui_TaskContainer2;
extern lv_obj_t * ui_labeltask2;
extern lv_obj_t * ui_DropdownTemperature2;
extern lv_obj_t * ui_DropdownCondition2;
extern lv_obj_t * ui_ConditionValue2;
extern lv_obj_t * ui_LabelDo2;
extern lv_obj_t * ui_DropdownAction2;
extern lv_obj_t * ui_ActionValue2;
extern lv_obj_t * ui_Keyboard3;
extern lv_obj_t * ui_TabPage3;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui____initial_actions0;








void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
