// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabView1 = lv_tabview_create(ui_Screen1, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_TabView1, 800);
    lv_obj_set_height(ui_TabView1, 480);
    lv_obj_set_x(ui_TabView1, -1);
    lv_obj_set_y(ui_TabView1, 0);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


    ui_TabPage1 = lv_tabview_add_tab(ui_TabView1, "DASHBOARD");

    ui_Container1 = lv_obj_create(ui_TabPage1);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, lv_pct(100));
    lv_obj_set_height(ui_Container1, lv_pct(100));
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Container6, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Connection: Not connected");

    ui_Container2 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_height(ui_Container2, 150);
    lv_obj_set_width(ui_Container2, lv_pct(100));
    lv_obj_set_align(ui_Container2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Chart2 = lv_chart_create(ui_Container2);
    lv_obj_set_width(ui_Chart2, lv_pct(70));
    lv_obj_set_height(ui_Chart2, lv_pct(100));
    lv_chart_set_type(ui_Chart2, LV_CHART_TYPE_LINE);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    ui_Chart2_series_1 = lv_chart_add_series(ui_Chart2, lv_color_hex(0x808080),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart2_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_Chart2, ui_Chart2_series_1, ui_Chart2_series_1_array);



    ui_Label1 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_Label1, 8);
    lv_obj_set_x(ui_Label1, lv_pct(-3));
    lv_obj_set_align(ui_Label1, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Label1, "SENSOR A\n40*F");
    lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, lv_pct(100));
    lv_obj_set_height(ui_Container3, LV_SIZE_CONTENT);    /// 11
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_Button1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Button1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Button1, 220);
    lv_obj_set_y(ui_Button1, 0);
    lv_obj_set_align(ui_Button1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelBtn1 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_LabelBtn1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBtn1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelBtn1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBtn1, "Compartment 1 Close");

    ui_Button2 = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_Button2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Button2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Button2, 220);
    lv_obj_set_y(ui_Button2, 0);
    lv_obj_set_align(ui_Button2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelBtn2 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_LabelBtn2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBtn2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelBtn2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBtn2, "Compartment 1 Open");

    ui_Button3 = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_Button3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Button3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Button3, 220);
    lv_obj_set_y(ui_Button3, 0);
    lv_obj_set_align(ui_Button3, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelBtn3 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_LabelBtn3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBtn3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelBtn3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBtn3, "Compartment 2 Close");

    ui_Button4 = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_Button4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Button4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Button4, 220);
    lv_obj_set_y(ui_Button4, 0);
    lv_obj_set_align(ui_Button4, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelBtn4 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_LabelBtn4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBtn4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelBtn4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBtn4, "Compartment 2 Open");

    ui_Label3 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label3, lv_pct(100));
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Log:");

    ui_TabPage2 = lv_tabview_add_tab(ui_TabView1, "TASKS");

    ui_Container4 = lv_obj_create(ui_TabPage2);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, lv_pct(100));
    lv_obj_set_height(ui_Container4, lv_pct(100));
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container4, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TaskContainer = lv_obj_create(ui_Container4);
    lv_obj_remove_style_all(ui_TaskContainer);
    lv_obj_set_width(ui_TaskContainer, lv_pct(100));
    lv_obj_set_height(ui_TaskContainer, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_flex_flow(ui_TaskContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TaskContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_TaskContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_labeltask = lv_label_create(ui_TaskContainer);
    lv_obj_set_height(ui_labeltask, 40);
    lv_obj_set_width(ui_labeltask, lv_pct(15));
    lv_obj_set_x(ui_labeltask, 40);
    lv_obj_set_y(ui_labeltask, 37);
    lv_obj_set_align(ui_labeltask, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labeltask, "TASK1: IF");
    lv_obj_set_style_text_align(ui_labeltask, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labeltask, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_labeltask, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_labeltask, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_labeltask, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_labeltask, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DropdownTemperature = lv_dropdown_create(ui_TaskContainer);
    lv_dropdown_set_options(ui_DropdownTemperature, "TEMPERATURE\nTEMPERATURE2\nHUMIDITY");
    lv_obj_set_width(ui_DropdownTemperature, lv_pct(20));
    lv_obj_set_height(ui_DropdownTemperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DropdownTemperature, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownTemperature, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_DropdownCondition = lv_dropdown_create(ui_TaskContainer);
    lv_dropdown_set_options(ui_DropdownCondition, ">\n<\n=");
    lv_obj_set_width(ui_DropdownCondition, lv_pct(8));
    lv_obj_set_height(ui_DropdownCondition, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DropdownCondition, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownCondition, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_ConditionValue = lv_textarea_create(ui_TaskContainer);
    lv_obj_set_width(ui_ConditionValue, 110);
    lv_obj_set_height(ui_ConditionValue, LV_SIZE_CONTENT);    /// 42
    lv_obj_set_x(ui_ConditionValue, 1);
    lv_obj_set_y(ui_ConditionValue, 0);
    lv_obj_set_align(ui_ConditionValue, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_ConditionValue, "50");
    lv_textarea_set_placeholder_text(ui_ConditionValue, "Placeholder...");
    lv_textarea_set_one_line(ui_ConditionValue, true);



    ui_LabelDo = lv_label_create(ui_TaskContainer);
    lv_obj_set_height(ui_LabelDo, 50);
    lv_obj_set_width(ui_LabelDo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_LabelDo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDo, "DO");
    lv_obj_set_style_text_align(ui_LabelDo, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDo, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelDo, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelDo, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelDo, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelDo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DropdownAction = lv_dropdown_create(ui_TaskContainer);
    lv_dropdown_set_options(ui_DropdownAction, "MOVE MOTOR 1\nMOVE MOTOR 2\nMOVE SERVO 1\nMOVE SERVO 2");
    lv_obj_set_width(ui_DropdownAction, lv_pct(20));
    lv_obj_set_height(ui_DropdownAction, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DropdownAction, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownAction, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_ActionValue = lv_textarea_create(ui_TaskContainer);
    lv_obj_set_width(ui_ActionValue, 111);
    lv_obj_set_height(ui_ActionValue, LV_SIZE_CONTENT);    /// 42
    lv_obj_set_x(ui_ActionValue, 1);
    lv_obj_set_y(ui_ActionValue, 0);
    lv_obj_set_align(ui_ActionValue, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_ActionValue, "45");
    lv_textarea_set_placeholder_text(ui_ActionValue, "Placeholder...");
    lv_textarea_set_one_line(ui_ActionValue, true);



    ui_TaskContainer1 = lv_obj_create(ui_Container4);
    lv_obj_remove_style_all(ui_TaskContainer1);
    lv_obj_set_width(ui_TaskContainer1, lv_pct(100));
    lv_obj_set_height(ui_TaskContainer1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_flex_flow(ui_TaskContainer1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TaskContainer1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_TaskContainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_labeltask1 = lv_label_create(ui_TaskContainer1);
    lv_obj_set_height(ui_labeltask1, 40);
    lv_obj_set_width(ui_labeltask1, lv_pct(15));
    lv_obj_set_x(ui_labeltask1, 40);
    lv_obj_set_y(ui_labeltask1, 37);
    lv_obj_set_align(ui_labeltask1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labeltask1, "TASK2: IF");
    lv_obj_set_style_text_align(ui_labeltask1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labeltask1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_labeltask1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_labeltask1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_labeltask1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_labeltask1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DropdownTemperature1 = lv_dropdown_create(ui_TaskContainer1);
    lv_dropdown_set_options(ui_DropdownTemperature1, "TEMPERATURE\nTEMPERATURE2\nHUMIDITY");
    lv_obj_set_width(ui_DropdownTemperature1, lv_pct(20));
    lv_obj_set_height(ui_DropdownTemperature1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DropdownTemperature1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownTemperature1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_DropdownCondition1 = lv_dropdown_create(ui_TaskContainer1);
    lv_dropdown_set_options(ui_DropdownCondition1, ">\n<\n=");
    lv_obj_set_width(ui_DropdownCondition1, lv_pct(8));
    lv_obj_set_height(ui_DropdownCondition1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DropdownCondition1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownCondition1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_ConditionValue1 = lv_textarea_create(ui_TaskContainer1);
    lv_obj_set_width(ui_ConditionValue1, 110);
    lv_obj_set_height(ui_ConditionValue1, LV_SIZE_CONTENT);    /// 42
    lv_obj_set_x(ui_ConditionValue1, 1);
    lv_obj_set_y(ui_ConditionValue1, 0);
    lv_obj_set_align(ui_ConditionValue1, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_ConditionValue1, "50");
    lv_textarea_set_placeholder_text(ui_ConditionValue1, "Placeholder...");
    lv_textarea_set_one_line(ui_ConditionValue1, true);



    ui_LabelDo1 = lv_label_create(ui_TaskContainer1);
    lv_obj_set_height(ui_LabelDo1, 50);
    lv_obj_set_width(ui_LabelDo1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_LabelDo1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDo1, "DO");
    lv_obj_set_style_text_align(ui_LabelDo1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDo1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelDo1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelDo1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelDo1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelDo1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DropdownAction1 = lv_dropdown_create(ui_TaskContainer1);
    lv_dropdown_set_options(ui_DropdownAction1, "MOVE MOTOR 1\nMOVE MOTOR 2\nMOVE SERVO 1\nMOVE SERVO 2");
    lv_obj_set_width(ui_DropdownAction1, lv_pct(20));
    lv_obj_set_height(ui_DropdownAction1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DropdownAction1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownAction1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_ActionValue1 = lv_textarea_create(ui_TaskContainer1);
    lv_obj_set_width(ui_ActionValue1, 111);
    lv_obj_set_height(ui_ActionValue1, LV_SIZE_CONTENT);    /// 42
    lv_obj_set_x(ui_ActionValue1, 1);
    lv_obj_set_y(ui_ActionValue1, 0);
    lv_obj_set_align(ui_ActionValue1, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_ActionValue1, "45");
    lv_textarea_set_placeholder_text(ui_ActionValue1, "Placeholder...");
    lv_textarea_set_one_line(ui_ActionValue1, true);



    ui_TaskContainer2 = lv_obj_create(ui_Container4);
    lv_obj_remove_style_all(ui_TaskContainer2);
    lv_obj_set_width(ui_TaskContainer2, lv_pct(100));
    lv_obj_set_height(ui_TaskContainer2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_flex_flow(ui_TaskContainer2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_TaskContainer2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_TaskContainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_labeltask2 = lv_label_create(ui_TaskContainer2);
    lv_obj_set_height(ui_labeltask2, 40);
    lv_obj_set_width(ui_labeltask2, lv_pct(15));
    lv_obj_set_x(ui_labeltask2, 40);
    lv_obj_set_y(ui_labeltask2, 37);
    lv_obj_set_align(ui_labeltask2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labeltask2, "TASK3: IF");
    lv_obj_set_style_text_align(ui_labeltask2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labeltask2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_labeltask2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_labeltask2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_labeltask2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_labeltask2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DropdownTemperature2 = lv_dropdown_create(ui_TaskContainer2);
    lv_dropdown_set_options(ui_DropdownTemperature2, "TEMPERATURE\nTEMPERATURE2\nHUMIDITY");
    lv_obj_set_width(ui_DropdownTemperature2, lv_pct(20));
    lv_obj_set_height(ui_DropdownTemperature2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DropdownTemperature2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownTemperature2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_DropdownCondition2 = lv_dropdown_create(ui_TaskContainer2);
    lv_dropdown_set_options(ui_DropdownCondition2, ">\n<\n=");
    lv_obj_set_width(ui_DropdownCondition2, lv_pct(8));
    lv_obj_set_height(ui_DropdownCondition2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DropdownCondition2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownCondition2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_ConditionValue2 = lv_textarea_create(ui_TaskContainer2);
    lv_obj_set_width(ui_ConditionValue2, 110);
    lv_obj_set_height(ui_ConditionValue2, LV_SIZE_CONTENT);    /// 42
    lv_obj_set_x(ui_ConditionValue2, 1);
    lv_obj_set_y(ui_ConditionValue2, 0);
    lv_obj_set_align(ui_ConditionValue2, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_ConditionValue2, "50");
    lv_textarea_set_placeholder_text(ui_ConditionValue2, "Placeholder...");
    lv_textarea_set_one_line(ui_ConditionValue2, true);



    ui_LabelDo2 = lv_label_create(ui_TaskContainer2);
    lv_obj_set_height(ui_LabelDo2, 50);
    lv_obj_set_width(ui_LabelDo2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_LabelDo2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDo2, "DO");
    lv_obj_set_style_text_align(ui_LabelDo2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDo2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelDo2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelDo2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelDo2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelDo2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DropdownAction2 = lv_dropdown_create(ui_TaskContainer2);
    lv_dropdown_set_options(ui_DropdownAction2, "MOVE MOTOR 1\nMOVE MOTOR 2\nMOVE SERVO 1\nMOVE SERVO 2");
    lv_obj_set_width(ui_DropdownAction2, lv_pct(20));
    lv_obj_set_height(ui_DropdownAction2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DropdownAction2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownAction2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags



    ui_ActionValue2 = lv_textarea_create(ui_TaskContainer2);
    lv_obj_set_width(ui_ActionValue2, 111);
    lv_obj_set_height(ui_ActionValue2, LV_SIZE_CONTENT);    /// 42
    lv_obj_set_x(ui_ActionValue2, 1);
    lv_obj_set_y(ui_ActionValue2, 0);
    lv_obj_set_align(ui_ActionValue2, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_ActionValue2, "45");
    lv_textarea_set_placeholder_text(ui_ActionValue2, "Placeholder...");
    lv_textarea_set_one_line(ui_ActionValue2, true);



    ui_Keyboard3 = lv_keyboard_create(ui_TabPage2);
    lv_keyboard_set_mode(ui_Keyboard3, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard3, lv_pct(40));
    lv_obj_set_height(ui_Keyboard3, lv_pct(50));
    lv_obj_set_align(ui_Keyboard3, LV_ALIGN_CENTER);

    ui_TabPage3 = lv_tabview_add_tab(ui_TabView1, "SETTINGS");

    ui_Container5 = lv_obj_create(ui_TabPage3);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, lv_pct(100));
    lv_obj_set_height(ui_Container5, lv_pct(100));
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard3, ui_ConditionValue);

}
